api_platform:
#  mapping:
#    paths: ['%kernel.project_dir%/api/config/api_platform/resources.yaml']
  formats:
#      jsonld:
#        mime_types:
#          - application/ld+json
      json:
        mime_types:
          - application/json
      html:
        mime_types:
          - text/html
  defaults:
    pagination_client_items_per_page: true

  doctrine:
    enabled: true
  doctrine_mongodb_odm:
    enabled: false