twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/main' : main
        '%kernel.project_dir%/templates/admin' : admin

when@test:
    twig:
        strict_variables: true
